CREATE TABLE accounts (
  id                      TEXT PRIMARY KEY,
  customer_name           TEXT NOT NULL,
  national_id             TEXT NOT NULL,
  phone_number            TEXT NOT NULL,
  device_id               TEXT UNIQUE NOT NULL REFERENCES devices(id),
  dealer_id               TEXT NOT NULL REFERENCES dealers(id),
  plan_id                 TEXT REFERENCES plans(id),
  total_loan_amount       INTEGER NOT NULL,
  amount_paid             INTEGER NOT NULL DEFAULT 0,
  daily_rate              INTEGER NOT NULL,
  next_payment_due        INTEGER NOT NULL,
  status                  TEXT NOT NULL DEFAULT 'ACTIVE',
  locked_by_dealer        INTEGER NOT NULL DEFAULT 0,
  down_payment            INTEGER NOT NULL,
  term_days               INTEGER NOT NULL,
  currency_code           TEXT NOT NULL DEFAULT 'GHS',
  release_approved        INTEGER NOT NULL DEFAULT 0,
  release_approved_at     INTEGER,
  released_at             INTEGER,
  device_hmac_secret      TEXT,
  device_hmac_secret_created_at INTEGER,
  customer_photo_path     TEXT,
  national_id_front_path  TEXT,
  national_id_back_path   TEXT,
  fcm_token               TEXT,
  fcm_token_updated_at    INTEGER,
  created_at              INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at              INTEGER NOT NULL DEFAULT (unixepoch())
);
