# Project-wide Gradle settings for SecurePay Customer app.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

TB_SUPPORT_PHONE=+233595012237
TB_SUPPORT_WHATSAPP=233595012237
TB_SUPPORT_EMAIL=adamutouchbase@gmail.com
