org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

TB_SUPPORT_PHONE=+233595012237
TB_SUPPORT_WHATSAPP=233595012237
TB_SUPPORT_EMAIL=adamutouchbase@gmail.com
